Repository ROCm/hipBLASLt, pull requests merged in 2024-09, with the labels that each got.

#1051 Aquavanjaram 942X HHS TN and NN GEMM size tuning
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: noCI, gfx94x

#1057 Used lazy initialization for the static variable to workaround the double-free symptom.
  tensilelite/Tensile/Source/lib/include/Tensile/ArithmeticUnitTypes.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/DataTypes.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/KernelLanguageTypes.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/PerformanceMetricTypes.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ScalarValueTypes.hpp
  tensilelite/Tensile/Source/lib/source/ArithmeticUnitTypes.cpp
  tensilelite/Tensile/Source/lib/source/DataTypes.cpp
  tensilelite/Tensile/Source/lib/source/KernelLanguageTypes.cpp
  tensilelite/Tensile/Source/lib/source/PerformanceMetricTypes.cpp
  tensilelite/Tensile/Source/lib/source/ScalarValueTypes.cpp
Labels: gfx94x

#1055 Fixed empty MatchTable.yaml if lazy loading enabled
  tensilelite/Tensile/TensileCreateLibrary.py
  utilities/find_exact.py
Labels: noCI

#1059 correct url
  docs/ext-ops.rst
Labels: ci:docs-only

#1060 correct url
  docs/ext-ops.rst
Labels: ci:docs-only

#1061 Added default code-reviewer
  CODEOWNERS
Labels: noCI

#1062 correct url
  docs/ext-ops.rst
Labels: ci:docs-only

#1065 Set compile option: fvisibility=hidden when building TensileHost
  library/src/amd_detail/rocblaslt/src/CMakeLists.txt
Labels: noCI

#893 Separate code object of matrix transform kernel from shared object
  library/src/amd_detail/rocblaslt/src/CMakeLists.txt
  library/src/amd_detail/rocblaslt/src/handle.cpp
  library/src/amd_detail/rocblaslt/src/kernels/CompileSourceKernel.cmake
  library/src/amd_detail/rocblaslt/src/kernels/compile_code_object.sh
  library/src/amd_detail/rocblaslt/src/kernels/matrix_transform.cpp
  library/src/amd_detail/rocblaslt/src/kernels/matrix_transform.h
  library/src/amd_detail/rocblaslt/src/kernels/matrix_transform.hpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_transform.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/KernelArguments.hpp
Labels: gfx94x

#1035 Stream-k initial support
  .gitignore
  clients/benchmarks/client_groupedgemm_fixed_mk.cpp
  clients/benchmarks/client_sequence.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/AsmStoreState.py
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Components/NotLocalFullTileElements.py
  tensilelite/Tensile/Components/PersistentLoop.py
  tensilelite/Tensile/Components/Signature.py
  tensilelite/Tensile/Components/StreamK.py
  tensilelite/Tensile/Components/__init__.py
  tensilelite/Tensile/Contractions.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/KernelWriterModules.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/client/source/SolutionIterator.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/AMDGPU.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionSolution_fwd.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Debug.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/GranularitySelectionLibrary.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/MasterSolutionLibrary.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/SingleSolutionLibrary.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/SolutionLibrary.hpp
  tensilelite/Tensile/Source/lib/source/AMDGPU.cpp
  tensilelite/Tensile/Source/lib/source/ContractionProblem.cpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
  tensilelite/Tensile/Source/lib/source/Debug.cpp
  tensilelite/Tensile/TensileInstructions/Instructions.py
  tensilelite/Tensile/TensileInstructions/RegisterPool.py
  tensilelite/Tensile/Tests/common/gsu/f32_gsu.yaml
  tensilelite/Tensile/Tests/common/streamk/sk_bgemm_quick.yaml
  tensilelite/Tensile/Tests/common/streamk/sk_hgemm_quick.yaml
  tensilelite/Tensile/Tests/common/streamk/sk_hgemm_race.yaml
  tensilelite/Tensile/Tests/common/streamk/sk_sgemm_quick.yaml
Labels: noCI, gfx94x

#1080 Update NonTemporal setting according to AsmCaps
  tensilelite/Tensile/SolutionStructs.py
Labels: noCI

#1082 Aquavanjaram942X F8F8S TN tuning to improve performance
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8F8S_BH_UserArgs.yaml
Labels: noCI, gfx94x

#1075 Using ref link to replace absoulte link
  docs/ext-ops.rst
  docs/samples/client_extop_softmax.rst
  docs/samples/sample_hipblaslt_ext_op_amax.rst
  docs/samples/sample_hipblaslt_ext_op_amax_with_scale.rst
  docs/samples/sample_hipblaslt_ext_op_layernorm.rst
Labels: documentation, ci:docs-only

#1025 [Enhance client's build time] Remove template type for testing_matmul_with_bias
  clients/common/cblas_interface.cpp
  clients/common/d_vector.cpp
  clients/include/allclose.hpp
  clients/include/argument_model.hpp
  clients/include/cblas_interface.hpp
  clients/include/d_vector.hpp
  clients/include/datatype_interface.hpp
  clients/include/flops.hpp
  clients/include/hipBuffer.hpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/hipblaslt_init.hpp
  clients/include/hipblaslt_random.hpp
  clients/include/hipblaslt_vector.hpp
  clients/include/near.hpp
  clients/include/norm.hpp
  clients/include/testing_matmul.hpp
  clients/include/type_dispatch.hpp
  clients/include/unit.hpp
Labels: noCI

#1102 Using ref link to replace absoulte link
  docs/ext-ops.rst
  docs/samples/client_extop_softmax.rst
  docs/samples/sample_hipblaslt_ext_op_amax.rst
  docs/samples/sample_hipblaslt_ext_op_amax_with_scale.rst
  docs/samples/sample_hipblaslt_ext_op_layernorm.rst
Labels: ci:docs-only

#1116 Update the descriptions for getHeuristic
  library/include/hipblaslt-ext.hpp
  library/include/hipblaslt.h
Labels: documentation, ci:docs-only

#1073 Reduce peak memory usage of TensileCreateLibrary
  tensilelite/Tensile/CustomYamlLoader.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterActivationFunction.py
  tensilelite/Tensile/LibraryIO.py
  tensilelite/Tensile/Parallel.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/TensileCreateLibrary.py
  tensilelite/Tensile/TensileInstructions/Base.py
  tensilelite/Tensile/cmake/TensileConfig.cmake
  tensilelite/requirements.txt
Labels: gfx94x

#1058 Make WorkGroupMappingXCC and WorkGroupMappingXCCGroup as GPU kernel arguments
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/README.md
  tensilelite/Tensile/Contractions.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
  tensilelite/Tensile/TensileInstructions/Instructions.py
  tensilelite/Tensile/TensileInstructions/Math.py
  tensilelite/Tensile/Tests/common/gemm/wgm.yaml
Labels: gfx94x

#1110 added kernels for BBS/HHS TN/NT/NN to equality for aquavanjaram942
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: noCI, gfx94x

#1127 Remove non-xnack+ for ASAN build
  CMakeLists.txt
Labels: gfx94x

#1126 Remove non-xnack+ for ASAN build
  CMakeLists.txt
Labels: gfx94x

#1141 Tune aquavanjaram942 HHS NN TN NT batched sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: noCI, gfx94x

#1132 Optimize ds read waitcnt for 1st iteration.
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
Labels: gfx94x

#1129 Fix default value for tensile logic build parameter
  install.sh
Labels: noCI

#1098 enable DirectToVgprA for f16/f32
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Components/LocalRead.py
  tensilelite/Tensile/Components/LraTileAssignment.py
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/KernelWriterModules.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/TensileInstructions/Instructions.py
  tensilelite/Tensile/Tests/common/gemm/dtv.yaml
  tensilelite/Tensile/Tests/common/gemm/dtv_gfx90a.yaml
Labels: gfx94x

#1151 Delay some LR instructions when the instruction FIFO is full.
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
Labels: gfx94x

#1153 Add DTVA custom kernel
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_F8BS_BH_BiasSB_AS_SABV_SAV_UserArgs_MT256x224x128_MI16x16x1_SN_K1_MIWT4_14_DTVA.s
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_F8BS_BH_BiasSB_AS_SABV_SAV_UserArgs_MT256x224x128_MI16x16x1_SN_K1_MIWT4_14_WSGRB2_DTVA.s
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_F8BS_BH_BiasSB_AS_SABV_SAV_UserArgs_MT256x256x128_MI16x16x1_SN_K1_MIWT4_16_DTVA.s
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_F8BS_BH_BiasSB_AS_SABV_SAV_UserArgs_MT256x256x128_MI16x16x1_SN_K1_MIWT4_16_WSGRB2_DTVA.s
  tensilelite/Tensile/Tests/common/gemm/gemm_ck_gfx942.yaml
Labels: gfx94x
