Repository ROCm/hipBLASLt, pull requests merged in 2024-07, with the labels that each got.

#881 Using ordered list reversed to instead dict reserved.
  tensilelite/Tensile/KernelWriter.py
Labels: gfx94x

#875 enable LSU + Int8
  tensilelite/Tensile/Components/PackData.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/TensileInstructions/ExtInstructions.py
  tensilelite/Tensile/Tests/common/gemm/lsu_i8.yaml
Labels: gfx94x

#888 Add Components README.md
  tensilelite/Tensile/Components/README.md
Labels: documentation, ci:docs-only

#890 Correct ScaleA/B behavior for mixed mode
  clients/common/cblas_interface.cpp
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Source/client/source/Reference.cpp
Labels: gfx94x

#883 Fix waitcnt and update TailLoop GR order of dtva custom kernel
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs_MT256x256x64_MI16x16x1_SN_K1_MIWT4_16_DTVA.s
Labels: gfx94x

#871 Tune aquavanjaram942 I8I8I TN memory bound GEMM sizes for CU80
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Alik_Bljk_I8BH_UserArgs.yaml
Labels: gfx94x

#880 Tune aquavanjaram942 SGEMM NN to get peak performance for CU80
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_SB_UserArgs.yaml
Labels: gfx94x

#690 pts-stage1: scripts for benchmarking perf.
  clients/benchmarks/client_extop_amax.cpp
  clients/include/argument_model.hpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/hipblaslt_common.yaml
  clients/include/testing_matmul.hpp
  clients/scripts/performance/bench.py
  clients/scripts/performance/generator.py
  clients/scripts/performance/git_info.py
  clients/scripts/performance/hipblaslt-perf
  clients/scripts/performance/problems/matmul_probset1_bench.yaml
  clients/scripts/performance/specs.py
  clients/scripts/performance/suites.py
Labels: enhancement

#898 Fix Lazy Lib Load to Improve Library Loading Time
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/PlaceholderLibrary.hpp
Labels: gfx94x

#894 Add an unrolled loop and swap GR/LW A/B order
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/ulsgro1.yaml
Labels: gfx94x

#901 fix mismatch issue with xfp32 + TLU + VectorWidth
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/Tests/common/gemm/xfp32.yaml
Labels: gfx94x

#917 Test: smaller K size for F8SS to prevent reporting accuracy error
  tensilelite/Tensile/Tests/common/gemm/fp8.yaml
Labels: gfx94x

#912 Add FP8 row-wise gemm (hipblaslt)
  clients/benchmarks/client.cpp
  clients/common/cblas_interface.cpp
  clients/common/hipblaslt_arguments.cpp
  clients/gtest/matmul_gtest.cpp
  clients/gtest/matmul_gtest.yaml
  clients/include/cblas_interface.hpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/hipblaslt_common.yaml
  clients/include/testing_matmul.hpp
  library/include/hipblaslt.h
  library/src/amd_detail/rocblaslt/include/rocblaslt-types.h
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_BiasSB_AS_SABV_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/include/handle.h
  library/src/amd_detail/rocblaslt/src/include/rocblaslt_mat_utils.hpp
  library/src/amd_detail/rocblaslt/src/include/tensile_host.hpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_mat.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  library/src/amd_detail/rocblaslt/src/utility.cpp
  tensilelite/Tensile/Tests/common/gemm/fp8.yaml
Labels: enhancement, gfx94x

#918 Add DTVA custom kernel
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs_MT256x256x64_MI16x16x1_SN_K1_MIWT4_16_WSGRB2_DTVA.s
Labels: gfx94x

#916 Fix missing lgkmcnt/ vmcnt after loading bias/scaleAlphaVec in n-dim case.
  tensilelite/Tensile/Components/GlobalWriteBatch.py
Labels: gfx94x

#932 Fix custom kernel name mismatch
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs_MT256x256x64_MI16x16x1_SN_K1_MIWT4_16_WSGRB2_DTVA.s
  tensilelite/Tensile/Tests/common/gemm/gemm_ck_gfx942.yaml
Labels: gfx94x

#895 Add MAC F64 Instruction to Support gfx11/gfx12
  clients/gtest/known_bugs.yaml
  clients/include/testing_matmul.hpp
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Ailk_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Ailk_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1201/Equality/gfx1201_Cijk_Ailk_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1201/Equality/gfx1201_Cijk_Ailk_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1201/Equality/gfx1201_Cijk_Alik_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1201/Equality/gfx1201_Cijk_Alik_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi31/Equality/navi31_Cijk_Ailk_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi31/Equality/navi31_Cijk_Ailk_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi31/Equality/navi31_Cijk_Alik_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi31/Equality/navi31_Cijk_Alik_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Ailk_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Ailk_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Alik_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Alik_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi33/Equality/navi33_Cijk_Ailk_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi33/Equality/navi33_Cijk_Ailk_Bljk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi33/Equality/navi33_Cijk_Alik_Bjlk_DB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi33/Equality/navi33_Cijk_Alik_Bljk_DB_UserArgs.yaml
  tensilelite/Tensile/Components/ComputeStoreVgprs.py
  tensilelite/Tensile/Components/MAC_F32.py
  tensilelite/Tensile/Components/MAC_F64.py
  tensilelite/Tensile/Tests/common/gemm/gfx11/f32_mac.yaml
  tensilelite/Tensile/Tests/common/gemm/gfx11/f64_mac.yaml
Labels: gfx94x

#929 gfx12 - bug fix in tail
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#962 Support different GRVWA and GRVWB for UnrollLoopSwapGlobalReadOrder.
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/ulsgro1.yaml
Labels: gfx94x
