Repository ROCm/hipBLASLt, pull requests merged in 2024-11, with the labels that each got.

#1300 Update ROCm versions on issue template
  .github/ISSUE_TEMPLATE/issue_report.yml
Labels: documentation, ci:docs-only

#1306 code-gen: Fixed DTVA code-gen and validation failures
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/dtv.yaml
Labels: bug, gfx94x

#1317 add 942 NN/NT/TN Equality sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#1314 Fix metadata accvgpr offset and next_free_vgpr usage
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/TensileInstructions/RegisterPool.py
Labels: gfx94x

#1310 Remove Duplicate 7900XTX from Issue Report
  .github/ISSUE_TEMPLATE/issue_report.yml
Labels: documentation, ci:docs-only

#1287 add TF32 sample code
  clients/samples/25_gemm_with_TF32/sample_hipblaslt_gemm_with_TF32.cpp
  clients/samples/CMakeLists.txt
  docs/api-reference.rst
Labels: gfx94x

#1304 Modify the condition to check resource.
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#1285 gfx12 - correct float operator for ocp fp8, remove redudent self impl…
  library/include/hipblaslt_float8.h
  tensilelite/Tensile/Source/lib/include/Tensile/DataTypes_Float8_BFloat8.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/hip_f8_impl.h
  tensilelite/Tensile/Source/tensile_float8_bfloat8.h
Labels: gfx94x

#1265 gfx12 - separate waitcnt for better perf.
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/TensileInstructions/Instructions.py
Labels: gfx94x

#1341 Fix dependency check in unrolled loop with numItersPLR == 0
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/TensileInstructions/Containers.py
Labels: gfx94x

#1302 GFX942 equality tuning for F8HS and F8B8HS for TN,NT,NN
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_F8B8HS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_F8B8HS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8B8HS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8HS_BH_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1376 Add gfx942 xf32 NN/NT/TN Equality yamls for 1105 xf32
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_S_MX_B_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_S_MX_B_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_S_MX_B_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1246 feature: DTV with Swizzling (tensorA)
  tensilelite/Tensile/BenchmarkProblems.py
  tensilelite/Tensile/ClientWriter.py
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Contractions.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionLibrary.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/client/include/ClientProblemFactory.hpp
  tensilelite/Tensile/Source/client/include/DataInitialization.hpp
  tensilelite/Tensile/Source/client/include/TensorDataManipulation.hpp
  tensilelite/Tensile/Source/client/main.cpp
  tensilelite/Tensile/Source/client/source/ClientProblemFactory.cpp
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionSolution.hpp
  tensilelite/Tensile/Tests/common/gemm/dtvA_swizzleA.yaml
Labels: enhancement, gfx94x

#1270 Tune Aquavanjaram942X F8F8S Equality TN 1 GEMM size
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8F8S_BH_UserArgs.yaml
Labels: gfx94x
