Repository ROCm/hipBLASLt, pull requests merged in 2024-04, with the labels that each got.

#718 fix cvt after ds schedule error
  tensilelite/Tensile/Components/LocalRead.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/Tests/common/gemm/mix_cvt_after_ds.yaml
Labels: gfx94x

#728 [CI] mark failed cases as xfail caused by llvm error
  tensilelite/Tensile/Tests/common/gemm/i8_gsu.yaml
  tensilelite/Tensile/Tests/common/gemm/i8_gsu_gfx940.yaml
Labels: gfx94x

#726 remove duplicated solutions of getAllAlgo
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
Labels: bug, gfx94x

#664 Fix matrix transform edge handling
  clients/gtest/matrix_transform_gtest.cpp
  library/src/amd_detail/rocblaslt/src/kernels/matrix_transform.hpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_transform.cpp
Labels: gfx94x

#732 update Equality BBS TN gfx942
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#733 update F8B8BS/F8BS/BBS yamls
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_Bias_BiasSrcB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8B8BS_BH_BiasB_AS_SAB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_BiasB_AS_SAB_SAV_UserArgs.yaml
Labels: gfx94x

#735 Update LSU logic yaml.
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_F8H_HHS_BH_Bias_AS_SAB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_F8H_HHS_BH_Bias_AS_SAB_SAV_custom.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_F8H_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_F8H_HHS_BH_custom.yaml
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#722 [HotFix] backward compabilities for 6.0 test tool
  CHANGELOG.md
  clients/gtest/matmul_gtest.yaml
  library/include/hipblaslt-ext.hpp
  library/src/amd_detail/hipblaslt-ext.cpp
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Ailk_Bljk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Alik_Bjlk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Alik_Bjlk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx940/GridBased/aquavanjaram_Cijk_Alik_Bljk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Ailk_Bljk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Alik_Bjlk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Alik_Bjlk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Alik_Bljk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_HSS_BH_Bias_GG_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
Labels: gfx94x

#719 Add INF Check in AmaxWithScale
  clients/gtest/hipblaslt_gtest_ext_op.cpp
  tensilelite/Tensile/Ops/AMaxGenerator.py
Labels: gfx94x

#737 Refactor hipBLASLt documentation
  LICENSE.md
  docs/api-reference.rst
  docs/clients.rst
  docs/datatypes.rst
  docs/ext-ops.rst
  docs/ext-reference.rst
  docs/index.rst
  docs/install.rst
  docs/installation.rst
  docs/logging-heuristics.rst
  docs/orga.rst
  docs/source-org.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-hipBLASLt.rst
Labels: ci:docs-only

#678 Support skinny I8 GEMM
  clients/gtest/matmul_gtest.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Ailk_Bjlk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Ailk_Bljk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Alik_Bjlk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Alik_Bljk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_I8II_BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_I8II_BH_AI_SAV_UserArgs.yaml
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#743 update CHANGELOG and lib version for 0.8.0
  CHANGELOG.md
  CMakeLists.txt
  README.md
Labels: ci:docs-only

#710 Add ForceDisableShadowInit
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Tests/common/gemm/no_shadowinit.yaml
Labels: gfx94x
