Repository ROCm/hipBLASLt, pull requests merged in 2024-12, with the labels that each got.

#1422 Temporarily remove some test cases for swizzle-A
  tensilelite/Tensile/Tests/common/gemm/dtvA_swizzleA.yaml
Labels: gfx94x

#1353 [OPT] Optimize tail loop
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#1433 LSU supports larger MT and reuse LDS.
  tensilelite/Tensile/Components/LSU.py
  tensilelite/Tensile/Components/__init__.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/TensileInstructions/Instructions.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#1459 gfx942_80cu BBS NN NT TN Tuning Release
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1421 code-gen: improved tail loop and edge tile of swizzled A
  tensilelite/Tensile/Contractions.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/dtvA_swizzleA.yaml
Labels: enhancement

#1460 Use archVGPR when accVGPR is not enough.
  tensilelite/Tensile/Components/LSU.py
  tensilelite/Tensile/Components/ShiftVectorComponents.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/KernelWriterModules.py
  tensilelite/Tensile/Tests/common/gemm/largeMT.yaml
Labels: gfx94x

#1492 Fix returnAlgoCount typo
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
Labels: gfx94x

#1494 Remove some Equality problems.
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8B8BS_BH_SAB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_SAB_UserArgs.yaml
Labels: gfx94x

#1497 Fixed random failures in MBSK post-loop
  tensilelite/Tensile/AsmAddressCalculation.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/TensileInstructions/Code.py
  tensilelite/Tensile/Tests/common/gemm/dtvA_swizzleA.yaml
Labels: gfx94x

#1503 update changelog
  CHANGELOG.md
Labels: ci:docs-only
