Repository ROCm/hipBLASLt, pull requests merged in 2024-10, with the labels that each got.

#1181 Fix arg object not exist in the beta only kernel.
  tensilelite/Tensile/KernelWriterBetaOnly.py
Labels: gfx94x

#1186 Update HIPBLASLT_ENABLE_MARKER
  docs/logging-heuristics.rst
Labels: documentation, noCI, ci:docs-only

#1178 Add tuning doc and update tuning utility
  docs/how-to-use-hipblaslt-tuning-utility.rst
  docs/images/hipblaslt-tuning-folder-structure.png
  docs/index.rst
  docs/sphinx/_toc.yml.in
  utilities/find_exact.py
  utilities/template.yaml
Labels: noCI, ci:docs-only

#1064 Correct URLs in the document
  docs/ext-ops.rst
Labels: documentation, ci:docs-only

#1194 Refine ProblemType check to prevent conflicts
  tensilelite/Tensile/Utilities/merge.py
Labels: gfx94x

#1196 Add batch support for hipblaslt-bench tuning
  utilities/find_exact.py
  utilities/template.yaml
Labels: noCI, ci:docs-only

#1173 Fix CI gfx11 I8 Fail - Add Local Read waitcnt for ScaleAlphaVec
  tensilelite/Tensile/Components/GlobalWriteBatch.py
Labels: gfx94x

#1224 update changelog for 6.3
  CHANGELOG.md
Labels: documentation, ci:docs-only

#1217 Update gfx942 BBS NN/NT/TN Equality yamls for amending 0911 sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#1204 enable DirectToVgprA/B step 2
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Components/LraTileAssignment.py
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/dtv.yaml
Labels: gfx94x

#1202 hipblaslt-bench performance improvements
  clients/CMakeLists.txt
  clients/common/hipblaslt_init_device.cpp
  clients/include/d_vector.hpp
  clients/include/hipBuffer.hpp
  clients/include/hipblaslt_init.hpp
  clients/include/hipblaslt_math.hpp
  clients/include/testing_matmul.hpp
Labels: gfx94x

#1218 Fix mismatch issue with GSU>255
  tensilelite/Tensile/KernelWriterConversion.py
Labels: gfx94x

#1240 Convert changelog to new format
  CHANGELOG.md
Labels: documentation, ci:docs-only

#1239 Use the same addrVgpr for all vectors in global store
  tensilelite/Tensile/AsmAddressCalculation.py
  tensilelite/Tensile/AsmStoreState.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/Components/StreamK.py
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#1235 fix: hipblaslt-bench output "non-supported type" when bias_type is no…
  clients/include/testing_matmul.hpp
Labels: gfx94x

#1244 Cherry-pick to release-staging/rocm-rel-6.3: Convert changelog to new format (#1240)
  CHANGELOG.md
Labels: documentation, ci:docs-only

#1228 re-enable DirectToLds
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/Components/StreamK.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/TensileInstructions/Base.py
  tensilelite/Tensile/TensileInstructions/Instructions.py
  tensilelite/Tensile/Tests/common/gemm/dtl.yaml
Labels: gfx94x

#1056 Revised output logic YAML to use efficiency instead of gflops.
  tensilelite/Tensile/LibraryLogic.py
  tensilelite/Tensile/Source/client/include/HardwareMonitor.hpp
  tensilelite/Tensile/Source/client/include/ResultReporter.hpp
  tensilelite/Tensile/Source/client/source/HardwareMonitor.cpp
  tensilelite/Tensile/Source/client/source/HardwareMonitorListener.cpp
  tensilelite/Tensile/Source/client/source/ResultFileReporter.cpp
Labels: gfx94x

#1230 enable DirectToVgpr + input type conversion
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/dtv.yaml
Labels: gfx94x

#1213 Fix lds bias offset out of range
  tensilelite/Tensile/AsmAddressCalculation.py
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#1250 Code refactoring
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/Parallel.py
  tensilelite/pytest.ini
Labels: gfx94x

#1245 Refine local read scheduling logic.
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
Labels: gfx94x

#1272 Add a condition to split local write.
  tensilelite/Tensile/Components/SIA.py
Labels: gfx94x

#1269 Add note pointing to the readme file plus metadata addition
  README.md
  docs/license.rst
Labels: documentation, ci:docs-only

#1278 hipblaslt-bench: new option "skip_slow_solution_ratio" to skip slow solution
  clients/benchmarks/client.cpp
  clients/benchmarks/program_options.hpp
  clients/common/hipblaslt_arguments.cpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/hipblaslt_common.yaml
  clients/include/testing_matmul.hpp
Labels: enhancement, gfx94x

#1282 Cherry-pick to release/rocm-rel-6.3: Clarify release and version number for 6.3.0 (#1255)
  CHANGELOG.md
Labels: documentation, ci:docs-only
