Repository ROCm/hipBLASLt, pull requests merged in 2024-05, with the labels that each got.

#751 Client: reduce template instances to speed up the build time
  clients/include/testing_matmul.hpp
Labels: gfx94x

#761 Fix LSU VGPR alignment.
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#763 Refactor tensilelite problem predicate and remove some hard hypothesi…
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/ContractionPredicates.hpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x

#764 BBS Equality update
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#745 Add labels for asm kernels indexing using symbol table
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#768 Remove Software prefetch custom kernel from solution pool
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/FreeSize/aquavanjaram_Cijk_Ailk_Bljk_F8H_HHS_BH_Bias_AS_SAB_SAV_freesize_custom_GSUs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/FreeSize/aquavanjaram_Cijk_Ailk_Bljk_F8H_HHS_BH_freesize_custom_GSUs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/FreeSize/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_Bias_AH_SAV_freesize_custom_GSUs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/FreeSize/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_freesize_custom_GSUs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/FreeSize/aquavanjaram_Cijk_Ailk_Bljk_HSS_BH_Bias_AS_SAV_Freesize_custom_GSUs.yaml
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_F8H_HHS_BH_Bias_AS_SAB_SAV_MT128x16x128_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_F8H_HHS_BH_Bias_AS_SAB_SAV_MT192x192x64_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_F8H_HHS_BH_Bias_AS_SAB_SAV_MT256x112x32_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_F8H_HHS_BH_MT128x16x128_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_HHS_BH_Bias_AS_SAV_MT32x16x16_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_HHS_BH_MT16x128x16_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_HHS_BH_MT16x128x16_MI16x16x1_prefetch2.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_HHS_BH_MT32x16x16_MI16x16x1_prefetch.s
  tensilelite/Tensile/CustomKernels/CustomGSUs_Cijk_Ailk_Bljk_HSS_BH_Bias_AS_SAV_MT16x16x256_MI16x16x1_prefetch.s
Labels: gfx94x

#765 Fix LSU bug for MIArchVGPR.
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#771 Fix rotating buffer bug when size is large.
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
  tensilelite/Tensile/Tests/common/gemm/large_size.yaml
Labels: gfx94x

#773 update Equality BBS gfx942 TN
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#777 restore some sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#782 Refactor hipBLASLt documentation (#737)
  LICENSE.md
  docs/api-reference.rst
  docs/clients.rst
  docs/datatypes.rst
  docs/ext-ops.rst
  docs/ext-reference.rst
  docs/index.rst
  docs/install.rst
  docs/installation.rst
  docs/logging-heuristics.rst
  docs/orga.rst
  docs/source-org.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-hipBLASLt.rst
Labels: ci:docs-only

#783 Seperate edge M and edge N
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#758 Update RTD config to use Python 3.10 and latest rocm-docs-core
  .readthedocs.yaml
  CODEOWNERS
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, dependencies, ci:docs-only

#778 Fix LSU bug.
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#776 Added hipblaslt_ext::matmulIsTuned API
  clients/samples/CMakeLists.txt
  clients/samples/gemm_tuning/sample_hipblaslt_gemm_is_tuned_ext.cpp
  library/include/hipblaslt-ext.hpp
  library/src/amd_detail/hipblaslt-ext.cpp
  library/src/amd_detail/rocblaslt/include/rocblaslt-functions.h
  library/src/amd_detail/rocblaslt/src/include/tensile_host.hpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ExactLogicLibrary.hpp
Labels: gfx94x

#791 add Equality F8BS gfx942 TN
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_BiasSB_AS_SAB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_SAB_UserArgs.yaml
Labels: gfx94x

#793 icache flush and rotating buffer in amax benchmark
  clients/benchmarks/client_extop_amax.cpp
  library/src/amd_detail/hipblaslt-ext-op.cpp
Labels: gfx94x
