Repository ROCm/hipBLASLt, pull requests merged in 2024-03, with the labels that each got.

#663 Enable F8/B8 for sparse
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/LocalRead.py
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
  tensilelite/Tensile/Tests/common/sparse/spmm_b8f8.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_b8f8_sb.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_bf8.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_bf8_sb.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_f8.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_f8_sb.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_f8b8.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_f8b8_sb.yaml
Labels: gfx94x

#674 gtest: Updated f8/b8 out test cases: some cases should use norm_check
  clients/gtest/matmul_gtest.yaml
  clients/include/norm.hpp
  library/include/hipblaslt_float8.h
Labels: gfx94x

#651 Add icache flush to bench
  clients/benchmarks/README.md
  clients/benchmarks/client.cpp
  clients/common/hipblaslt_arguments.cpp
  clients/include/argument_model.hpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/hipblaslt_common.yaml
  clients/include/testing_matmul.hpp
Labels: gfx94x

#676 [Client] Support test parameter c_equal_d in hipblaslt-bench
  clients/benchmarks/README.md
  clients/benchmarks/client.cpp
  clients/common/hipblaslt_arguments.cpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/testing_matmul.hpp
  docs/clients.rst
Labels: gfx94x

#669 Add sequence client
  clients/benchmarks/CMakeLists.txt
  clients/benchmarks/client_sequence.cpp
  clients/benchmarks/sequence.yaml
  clients/include/utility.hpp
  library/src/include/auxiliary.hpp
Labels: gfx94x

#675 enable NN/NT/TN/TT for convert after DS
  tensilelite/Tensile/Components/LocalRead.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#680 Add sequence client (stable)
  clients/benchmarks/CMakeLists.txt
  clients/benchmarks/client_sequence.cpp
  clients/benchmarks/sequence.yaml
  clients/include/utility.hpp
  library/src/include/auxiliary.hpp
Labels: gfx94x

#682 Enable SingleBuffer
  tensilelite/Tensile/Components/NotLocalFullTileElements.py
  tensilelite/Tensile/Contractions.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
  tensilelite/Tensile/Tests/common/gemm/gsuasb.yaml
Labels: gfx94x

#635 [Gfx11xx] fix build break
  tensilelite/Tensile/KernelWriterConversion.py
  tensilelite/Tensile/Ops/SoftmaxGenerator.py
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#681 Add Tensile_BUILD_ID for setting the specific build id kind
  CMakeLists.txt
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/Ops/gen_assembly.sh
  tensilelite/Tensile/Source/TensileCreateLibrary.cmake
  tensilelite/Tensile/TensileCreateLibrary.py
  tensilelite/Tensile/TensileInstructions/Utils.py
  tensilelite/Tensile/cmake/TensileConfig.cmake
Labels: gfx94x

#254 Support logic json format in TensileLite
  tensilelite/Tensile/BenchmarkProblems.py
  tensilelite/Tensile/ClientWriter.py
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/LibraryIO.py
  tensilelite/Tensile/LibraryLogic.py
  tensilelite/Tensile/Tensile.py
  tensilelite/Tensile/TensileClientConfig.py
  tensilelite/Tensile/TensileCreateLibrary.py
  tensilelite/Tensile/TensileRetuneLibrary.py
  tensilelite/requirements.txt
Labels: enhancement

#686 Update TN BF16BF16 Performance of Remained Sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#684 Update TN F8BF16 Performance of Remained Sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_UserArgs.yaml
Labels: gfx94x

#685 Add missing BSS dispatch type
  clients/gtest/matmul_gtest.yaml
  clients/include/hipblaslt_common.yaml
  clients/include/type_dispatch.hpp
Labels: gfx94x

#691 Fix Equality Yaml Typo
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8BS_BH_UserArgs.yaml
Labels: gfx94x

#692 add tox test of mix precision convert after DS
  tensilelite/Tensile/Tests/common/gemm/mix_cvt_after_ds.yaml
Labels: gfx94x

#647 Add Lazy Library Loading
  CMakeLists.txt
  clients/benchmarks/client_sequence.cpp
  clients/include/testing_matmul.hpp
  clients/samples/gemm_get_algo_by_index/sample_hipblaslt_gemm_get_algo_by_index_ext.cpp
  docs/usage.rst
  library/include/hipblaslt-ext.hpp
  library/src/amd_detail/rocblaslt/src/CMakeLists.txt
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/MasterSolutionLibrary.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/PlaceholderLibrary.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/PlaceholderLibrary.hpp
  tensilelite/Tensile/Source/lib/source/ContractionProblem.cpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x

#700 Fix Redheat can't setup vm properly
  cmake/virtualenv.cmake
Labels: gfx94x

#702 add tox test of mix precision convert after DS
  tensilelite/Tensile/Tests/common/gemm/mix_cvt_after_ds.yaml
Labels: gfx94x

#704 use integer to replace trig init in mix tox test
  tensilelite/Tensile/Tests/common/gemm/mix_cvt_after_ds.yaml
Labels: gfx94x

#712 fix convert after ds error
  tensilelite/Tensile/Components/LocalRead.py
Labels: gfx94x

#711 Fix AmaxWithScale Random Fail
  clients/gtest/hipblaslt_gtest_ext_op.cpp
  tensilelite/Tensile/Ops/AMaxGenerator.py
Labels: gfx94x

#701 [Tensilelite][Sparse] half the available size of the structured sparsity matrix data size.
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x

#703 Extend LSU Support.
  tensilelite/Tensile/AsmAddressCalculation.py
  tensilelite/Tensile/AsmStoreState.py
  tensilelite/Tensile/Components/ComputeStoreVgprs.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/Components/NotLocalFullTileElements.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#714 Update CHANGELOG.md
  CHANGELOG.md
Labels: noCI

#715 LSU to support GSU and other global write features.
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#696 fix ws allocation in hipblaslt-bench
  clients/include/testing_matmul.hpp
Labels: gfx94x

#720 Rewrite defineAndResources to avoid data hazard
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x
