Repository ROCm/hipBLASLt, pull requests merged in 2024-08, with the labels that each got.

#940 Fix I8I8I SDWA Fail for gfx12
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/Components/PackData.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Tests/common/gemm/gfx12/i8_gsu_gfx12.yaml
Labels: gfx94x

#973 Add GemmPreferenceV2 and GemmTuningV2 for backward compatibility
  clients/benchmarks/client_sequence.cpp
  clients/include/testing_auxiliary.hpp
  clients/include/testing_matmul.hpp
  clients/samples/gemm/sample_hipblaslt_gemm_ext.cpp
  clients/samples/gemm/sample_hipblaslt_gemm_ext_bgradb.cpp
  clients/samples/gemm_alphavec/sample_hipblaslt_gemm_alphavec_ext.cpp
  clients/samples/gemm_get_algo_by_index/sample_hipblaslt_gemm_get_algo_by_index_ext.cpp
  clients/samples/gemm_get_all_algos/sample_hipblaslt_gemm_get_all_algos_ext.cpp
  clients/samples/gemm_mix_precision/sample_hipblaslt_gemm_mix_precision_ext.cpp
  clients/samples/gemm_mix_precision/sample_hipblaslt_gemm_mix_precision_with_amax_ext.cpp
  clients/samples/gemm_tuning/sample_hipblaslt_gemm_tuning_splitk_ext.cpp
  clients/samples/gemm_tuning/sample_hipblaslt_gemm_tuning_wgm_ext.cpp
  clients/samples/groupedgemm/sample_hipblaslt_groupedgemm_ext.cpp
  clients/samples/groupedgemm_fixed_mk/sample_hipblaslt_groupedgemm_fixed_mk_ext.cpp
  clients/samples/groupedgemm_get_all_algos/sample_hipblaslt_groupedgemm_get_all_algos_ext.cpp
  docs/ext-reference.rst
  library/include/hipblaslt-ext.hpp
  library/src/amd_detail/hipblaslt-ext.cpp
  library/src/amd_detail/rocblaslt/include/rocblaslt-auxiliary.h
  library/src/amd_detail/rocblaslt/include/rocblaslt-functions.h
  library/src/amd_detail/rocblaslt/include/rocblaslt-types.h
  library/src/amd_detail/rocblaslt/src/include/tensile_host.hpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_mat.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
Labels: enhancement, help wanted, gfx94x

#972 Support Azure Linux 3.x
  CMakeLists.txt
  clients/include/testing_matmul.hpp
  install.sh
  tensilelite/Tensile/Source/client/CMakeLists.txt
  tensilelite/Tensile/Source/client/source/ClientProblemFactory.cpp
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
  tensilelite/Tensile/Source/client/source/HardwareMonitor.cpp
  tensilelite/Tensile/Source/lib/CMakeLists.txt
  tensilelite/Tensile/Source/lib/include/Tensile/Serialization/MatchingLibrary.hpp
Labels: gfx94x

#965 Fix Lazy Load for Code Objects
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/PlaceholderLibrary.hpp
Labels: gfx94x

#998 update documentation of hipblaslt
  library/include/hipblaslt.h
Labels: ci:docs-only

#994 Enable HardwareMonitor for gfx94x.
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Source/client/include/HardwareMonitor.hpp
  tensilelite/Tensile/Source/client/source/HardwareMonitor.cpp
Labels: gfx94x

#999 update documentation
  library/include/hipblaslt.h
Labels: ci:docs-only

#1006 update BBS TT gridbased for gfx942
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_BBS_BH_Bias_AH_SAV.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_BBS_BH_Bias_AS_SAV_UserArgs.yaml
Labels: gfx94x

#1005 gridbased batch experiment
  tensilelite/Tensile/Source/lib/include/Tensile/Debug.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/PropertyMatching.hpp
  tensilelite/Tensile/Source/lib/source/Debug.cpp
Labels: gfx94x

#1014 Enable WGM=-1.
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Tests/common/gemm/wgm.yaml
Labels: gfx94x

#1022 Change ScaleABVec from global read to LDS
  tensilelite/Tensile/AsmAddressCalculation.py
  tensilelite/Tensile/AsmStoreState.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Tests/common/gemm/fp8.yaml
  tensilelite/Tensile/Tests/common/gemm/fp8_rowwise.yaml
Labels: gfx94x

#1016 Add Navi32 Logic Yamls TN/NN BBS/HHS
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Ailk_Bljk_BBS_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Ailk_Bljk_HHS_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Alik_Bljk_BBS_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/navi32/Equality/navi32_Cijk_Alik_Bljk_HHS_UserArgs.yaml
Labels: noCI

#1033 Set MAX_OMP_THREADS for CI Stablility
  tensilelite/Tensile/Source/client/source/Reference.cpp
Labels: noCI

#1037 Remove deepcopies in TensileCreateLibrary
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/TensileCreateLibrary.py
Labels: gfx94x

#1040 Use different getFile function that doesn't trigger segfault
  tensilelite/Tensile/Source/lib/source/llvm/Loading.cpp
Labels: noCI

#1032 Enable WGM=-1 in ContractionSolution.
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: noCI, gfx94x

#1029 Supported small size (M,N,K<8) and added to gtest for F8/BF8 in/out combinations
  clients/gtest/matmul_gtest.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_B8F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_B8F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_F8B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_F8B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_B8F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_B8F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_F8B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_F8B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_B8F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_B8F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_F8B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_F8B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_B8F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_B8F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8B8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8B8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8B8S_BH_BiasSHB_AS_SAB_SCD_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8F8S_BH_BiasSH_AS_SAB_SCD_SAV_UserArgs.yaml
Labels: gfx94x

#1002 Add dtva custom kernels: MT256x224x64
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs_MT256x224x64_MI16x16x1_SN_K1_MIWT4_14_DTVA.s
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs_MT256x224x64_MI16x16x1_SN_K1_MIWT4_14_WSGRB2_DTVA.s
  tensilelite/Tensile/Tests/common/gemm/gemm_ck_gfx942.yaml
Labels: gfx94x

#1031 Moved TensileCreateLibrary artifacts to runtime package
  library/CMakeLists.txt
Labels: noCI, gfx94x

#1021 Added F8HS / HHS TN Equality kernels for gfx942
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8HS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: gfx94x

#1030 Fix write yaml for sparse tuning
  tensilelite/Tensile/LibraryIO.py
  tensilelite/Tensile/TensileCreateLibrary.py
  tensilelite/Tensile/TensileUpdateLibrary.py
  tensilelite/Tensile/Tests/common/sparse/libray_logic.yaml
Labels: noCI, gfx94x

#1046 Update gfx942 BBS TN Equality yaml to fix disagg prefill regression
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs.yaml
Labels: noCI, gfx94x

#1052 Update gfx942 Equality BBS NN/NT yamls for 0822 non-llm sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_Bias_AS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_Bias_AS_SAV_UserArgs.yaml
Labels: noCI, gfx94x
