Repository ROCm/hipBLASLt, pull requests merged in 2024-06, with the labels that each got.

#794 Fix Universal PostGSU
  tensilelite/Tensile/KernelWriterConversion.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x

#802 Force bias pointer set to nullptr in tensile_host.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
Labels: gfx94x

#812 update doc for hipblasLtMatmulHeuristicResult_t
  library/include/hipblaslt.h
Labels: ci:docs-only

#813 update doc for hipblasLtMatmulHeuristicResult_t
  library/include/hipblaslt.h
Labels: ci:docs-only

#817 Fix LSU/edge bug
  tensilelite/Tensile/AsmStoreState.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Tests/common/gemm/lsu.yaml
Labels: gfx94x

#815 Tune aquavanjaram942 80cu HHS and BBS NN memory bound GEMM sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
Labels: gfx94x

#668 Enable precision INT8 in hipBLASLt
  CHANGELOG.md
  README.md
  clients/benchmarks/README.md
  clients/benchmarks/client.cpp
  clients/common/cblas_interface.cpp
  clients/gtest/matmul_gtest.yaml
  clients/include/hipblaslt_common.yaml
  clients/include/testing_matmul.hpp
  clients/include/type_dispatch.hpp
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Ailk_Bjlk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Ailk_Bljk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Alik_Bjlk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/104CU/GridBased/aldebaran_Cijk_Alik_Bljk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/110CU/GridBased/aldebaran_Cijk_Ailk_Bjlk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/110CU/GridBased/aldebaran_Cijk_Ailk_Bljk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/110CU/GridBased/aldebaran_Cijk_Alik_Bjlk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aldebaran/110CU/GridBased/aldebaran_Cijk_Alik_Bljk_I8BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Ailk_Bljk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Alik_Bjlk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx941/GridBased/aquavanjaram_Cijk_Alik_Bljk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bjlk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Ailk_Bljk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bjlk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_I8BH_AI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/include/rocblaslt_mat_utils.hpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x

#823 Fix: workspace size of preference descriptor is set as 0 unexpectedly
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
Labels: bug, gfx94x

#821 Fix rotating buffer bug in tensile client
  tensilelite/Tensile/Source/client/include/DataInitialization.hpp
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
Labels: bug

#822 Fix: workspace size of preference descriptor is set as 0 unexpectedly
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
Labels: bug, gfx94x

#804 Amax codegen: improved tail block
  tensilelite/Tensile/Ops/AMaxGenerator.py
Labels: gfx94x

#807 Support mariner OS
  CMakeLists.txt
  install.sh
Labels: gfx94x

#818 CI: Add new test to verify all returned solutions of heuristic/getAll
  clients/gtest/matmul_gtest.yaml
  clients/include/testing_matmul.hpp
Labels: gfx94x

#826 MBSK extend coverage
  library/src/amd_detail/hipblaslt.cpp
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/client/source/ClientProblemFactory.cpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
Labels: gfx94x

#833 Fix missing typeid symbol errror when using clang++
  library/include/hipblaslt-ext.hpp
  library/src/amd_detail/hipblaslt-ext.cpp
Labels: bug, gfx94x

#838 gtest fix for int8_matmul
  clients/common/cblas_interface.cpp
  clients/gtest/matmul_gtest.yaml
  clients/include/testing_matmul.hpp
  clients/include/utility.hpp
Labels: gfx94x

#842 gfx942 80cu BBS/HHS NN/NT/TN Equality tuning
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: gfx94x

#847 fix divide zero error
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#824 Optimize GSU Workgroup Assignment
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/TensileInstructions/Math.py
  tensilelite/Tensile/Tests/common/gemm/gsuc.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_gsuc.yaml
Labels: gfx94x

#849 update documentation for matmulIsAlgoSupported()
  library/include/hipblaslt-ext.hpp
Labels: ci:docs-only

#830 Amax codegen: odd-size-tail
  clients/benchmarks/client_extop_amax.cpp
  tensilelite/Tensile/Ops/AMaxGenerator.py
Labels: gfx94x

#851 Fix errors when calculating ldsPad and ldsNumBytes of sparse metadata.
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#850 Fix the condition of adding the missing sizes to nonRotatingSize
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
  tensilelite/Tensile/Tests/common/client/rotate.yaml
Labels: bug, gfx94x

#841 [Tensilelite] Enable I8/B/S for Sparse MM
  tensilelite/Tensile/Common.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/Source/client/include/TypedId.hpp
  tensilelite/Tensile/Source/client/source/Reference.cpp
  tensilelite/Tensile/Tests/common/sparse/spmm_i8bs.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_i8bs_sb.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_i8is.yaml
  tensilelite/Tensile/Tests/common/sparse/spmm_i8is_sb.yaml
Labels: gfx94x

#846 Set inputs in GemmInputs to pointers to const
  library/include/hipblaslt-ext.hpp
Labels: gfx94x

#789 Tensilelite icache flush
  tensilelite/Tensile/BenchmarkProblems.py
  tensilelite/Tensile/BenchmarkStructs.py
  tensilelite/Tensile/ClientWriter.py
  tensilelite/Tensile/Source/client/include/BenchmarkTimer.hpp
  tensilelite/Tensile/Source/client/include/ClientProblemFactory.hpp
  tensilelite/Tensile/Source/client/main.cpp
  tensilelite/Tensile/Source/client/source/BenchmarkTimer.cpp
  tensilelite/Tensile/Tests/common/gemm/icache_flush.yaml
Labels: gfx94x

#858 gfx942 80cu Add custom kernel with triple buffer algorithm
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_HHS_BH_UserArgs_MT128x16x128_MI16x16x1_SN_K1_MIWT2_1_triple_buffer.s
Labels: gfx94x

#828 Tune aquavanjaram942 80CU compute bound and memory bound HHS NN GEMM sizes
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
Labels: gfx94x

#864 fix incorrect calcLdsNumBytes calculation
  tensilelite/Tensile/SolutionStructs.py
Labels: gfx94x

#865 Add allclose funtion to bench
  clients/benchmarks/client.cpp
  clients/common/hipblaslt_arguments.cpp
  clients/include/allclose.hpp
  clients/include/argument_model.hpp
  clients/include/hipblaslt_arguments.hpp
  clients/include/hipblaslt_common.yaml
  clients/include/testing_matmul.hpp
Labels: gfx94x

#869 Reorder global load instructions of dtva custom kernel
  tensilelite/Tensile/CustomKernels/Custom_Cijk_Alik_Bljk_BBS_BH_Bias_AS_SAV_UserArgs_MT256x256x64_MI16x16x1_SN_K1_MIWT4_16_DTVA.s
  tensilelite/Tensile/Tests/common/gemm/gemm_ck_gfx942.yaml
Labels: gfx94x
