Repository ROCm/hipBLASLt, pull requests merged in 2025-05, with the labels that each got.

#2018 Add copyright into rocroller host (#1994)
  library/src/amd_detail/rocblaslt/src/include/rocroller_host.hpp
  library/src/amd_detail/rocblaslt/src/rocroller_host.cpp
Labels: ci:docs-only

#2009 Enabling LDS>64K for LocalReadVALU
  tensilelite/Tensile/Components/LocalRead.py
Labels: gfx950

#2036 gfx942 equality add BBS/TN 8192,2048,3584
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#2045 gfx942 80cu add 5 sizes equality
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942_80cu/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
Labels: gfx94x

#1681 GSU Reduction Optimization
  tensilelite/Tensile/AsmStoreState.py
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  tensilelite/Tensile/Source/lib/source/ContractionProblem.cpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x, runPerformance, gfx950

#2053 [next-cmake] Add rocm cmake
  next-cmake/CMakeLists.txt
Labels: noCI

#2058 [next-cmake] Restore asan builds in next-cmake
  next-cmake/CMakeLists.txt
  next-cmake/clients/CMakeLists.txt
  next-cmake/clients/samples/CMakeLists.txt
  next-cmake/cmake/hipblaslt_python.cmake
  next-cmake/cmake/hipblaslt_target_configure_sanitizers.cmake
  next-cmake/device-library/CMakeLists.txt
Labels: noCI

#2068 [next-cmake] Add coverage to next-cmake
  next-cmake/CMakeLists.txt
Labels: noCI

#2059 [next-cmake] legacy hipblast direct
  next-cmake/CMakeLists.txt
Labels: noCI

#2078 [next-cmake] Disable marker library on Windows
  next-cmake/CMakeLists.txt
Labels: noCI

#2087 [next-cmake] Required updates to next-cmake discovered during install script integration
  next-cmake/CMakeLists.txt
  next-cmake/clients/CMakeLists.txt
  next-cmake/clients/samples/01_hipblaslt_gemm_ext_deprecated/CMakeLists.txt
  next-cmake/clients/samples/CMakeLists.txt
  next-cmake/cmake/FindBLIS.cmake
  next-cmake/device-library/CMakeLists.txt
Labels: noCI

#2074 [next-cmake] Remove indirect dependencies
  next-cmake/clients/CMakeLists.txt
Labels: noCI

#2090 Fix SIA bug in gfx950
  tensilelite/Tensile/Components/SIA.py
  tensilelite/Tensile/KernelWriter.py
Labels: gfx950

#2093 Add batch size to workspace allocation
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x, gfx950

#2047 Add new MLPNet experimental libraries
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bjlk_F8HS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bjlk_SB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bljk_F8HS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Ailk_Bljk_SB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bjlk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bjlk_F8HS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bjlk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bjlk_SB_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bljk_F8HS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Experimental/MLPNet/aquavanjaram_Cijk_Alik_Bljk_SB_UserArgs.yaml
  tensilelite/Tensile/Source/lib/source/MLPNet.cpp
Labels: gfx94x

#2072 Restructure SrdTDInit and refine GSUMBSK
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/Components/GlobalWriteBatch.py
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x, gfx950

#2115 Detected CU-Fallback case and then overwrite xcc values.
  library/src/amd_detail/hipblaslt-ext-op-internal.hpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  tensilelite/Tensile/Hardware.py
  tensilelite/Tensile/Source/lib/include/Tensile/AMDGPU.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblem.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/ContractionSolution.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/Tensile.hpp
  tensilelite/Tensile/Source/lib/source/AMDGPU.cpp
  tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
Labels: gfx94x

#2130 Use standard way HIPBLASLT_MATMUL_MATRIX_SCALE_OUTER_VEC_32F to enabl…
  clients/include/testing_matmul.hpp
  library/include/hipblaslt/hipblaslt.h
  library/src/amd_detail/rocblaslt/include/rocblaslt-types.h
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/utility.cpp
Labels: gfx950

#2145 Enable multiple vgprs for local r/w + storeswapaddr
  tensilelite/Tensile/KernelWriter.py
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx950
