Repository ROCm/hipBLASLt, pull requests merged in 2025-04, with the labels that each got.

#1853 update lib version
  CMakeLists.txt
Labels: ci:docs-only

#1854 update lib version
  CMakeLists.txt
Labels: ci:docs-only

#1850 perf: Supported multi-samples for PTS to calc significance value (p-value)
  clients/scripts/performance/bench_sample.py
  clients/scripts/performance/hipblaslt-perf
Labels: runPerformance

#1925 Add copyright
  library/src/amd_detail/rocblaslt/src/UserDrivenTuningParser.cpp
  library/src/amd_detail/rocblaslt/src/include/UserDrivenTuningParser.hpp
  tensilelite/HostLibraryTests/configs/SolutionLibraries/readme
  tensilelite/Tensile/CustomKernels/README.md
  tensilelite/Tensile/SolutionStructs/__init__.py
  tensilelite/Tensile/Tests/common/gemm/gfx12/b8f8ss_grvw1_gfx12.yaml
  tensilelite/Tensile/Tests/common/gemm/gfx12/b8hs_grvw1_gfx12.yaml
  tensilelite/Tensile/Tests/common/gemm/gfx12/f8f8s_grvw1_gfx12.yaml
  tensilelite/Tensile/Tests/common/gemm/gfx12/i8i8i_grvw1_gfx12.yaml
  tensilelite/Tensile/Tests/common/gemm/gfx12/i8ii_grvw1_gfx12.yaml
  tensilelite/Tensile/Tests/unit/test_MatrixInstructionConversion.py
  tensilelite/Tensile/Toolchain/Component.py
Labels: ci:docs-only

#1894 Added dot2bf16 instructions
  tensilelite/Tensile/Components/MAC_BF16_HPA.py
  tensilelite/Tensile/Components/SumUnroll.py
  tensilelite/Tensile/SolutionStructs/Solution.py
  tensilelite/Tensile/Tests/common/gemm/gfx950/dot2_gfx950.yaml
  tensilelite/Tensile/Tests/common/gradient/gfx950/bf16_gradient_bias.yaml
  tensilelite/rocisa/rocisa/include/hardware_caps.hpp
  tensilelite/rocisa/rocisa/include/instruction/common.hpp
  tensilelite/rocisa/rocisa/src/instruction/common.cpp
Labels: Feature Request

#1964 update gfx1200 logic
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8B8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8BH_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8BS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8B8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8BH_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8BS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8F8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8HS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8SS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8F8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8HS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_B8SS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_BBS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_BSS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8B8B8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8B8BS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8B8F8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8B8HS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8B8SS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8B8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8BS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8F8S_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8HS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_F8SS_BH_BiasS_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_HHS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_HSS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_I8BH_HAI_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx1200/Equality/gfx1200_Cijk_Alik_Bljk_I8II_HAI_SAV_UserArgs.yaml
Labels: noTensileLogic

#1976 Add 6.4.1 changelog entry and bump version number
  CHANGELOG.md
  CMakeLists.txt
Labels: documentation, noCI, ci:docs-only

#1994 Add copyright into rocroller host
  library/src/amd_detail/rocblaslt/src/include/rocroller_host.hpp
  library/src/amd_detail/rocblaslt/src/rocroller_host.cpp
Labels: ci:docs-only

#1996 [next-cmake] Make BLIS actually optional.
  next-cmake/CMakeLists.txt
Labels: noCI

#1997 [cmake-next] Make final tweaks needed to build as part of TheRock.
  next-cmake/CMakeLists.txt
  next-cmake/clients/CMakeLists.txt
  next-cmake/clients/common/src/CMakeLists.txt
  next-cmake/cmake/hipblaslt_python.cmake
  next-cmake/device-library/CMakeLists.txt
  next-cmake/device-library/extops/CMakeLists.txt
  tensilelite/Tensile/TensileCreateLibrary/__main__.py
Labels: noCI

#2004 [cmake-next] Refine TensileCreate build step.
  next-cmake/device-library/CMakeLists.txt
Labels: noCI
