Repository ROCm/hipBLASLt, pull requests merged in 2025-03, with the labels that each got.

#1703 PTS: Replaced the latest git_info.py from rocPTS
  clients/scripts/performance/git_info.py
Labels: runPerformance

#1696 We need hipblas-common-static for static-devel builds
  CMakeLists.txt
  tensilelite/Tensile/Source/client/CMakeLists.txt
  tensilelite/Tensile/Tensile.py
  tensilelite/requirements.txt
Labels: ci:static-libraries

#1704 Updated documents for swizzle support
  docs/api-reference.rst
  library/include/hipblaslt.h
Labels: ci:docs-only

#1749 Change cmake create package description
  CMakeLists.txt
Labels: noCI, ci:docs-only

#1664 docs: refactor hipBLASLt docs
  docs/conceptual/hipblaslt-clients.rst
  docs/conceptual/hipblaslt-library-organization.rst
  docs/ext-ops.rst
  docs/how-to-use-hipblaslt-tuning-utility.rst
  docs/how-to/how-to-use-hipblaslt-offline-tuning.rst
  docs/how-to/how-to-use-hipblaslt-tuning-utility.rst
  docs/how-to/how-to-use-streamk.rst
  docs/how-to/use-logging-heuristics.rst
  docs/index.rst
  docs/install/building-installing-hipblaslt.rst
  docs/installation.rst
  docs/logging-heuristics.rst
  docs/reference/api-reference.rst
  docs/reference/datatypes.rst
  docs/reference/ext-ops.rst
  docs/reference/ext-reference.rst
  docs/samples/client_extop_softmax.rst
  docs/samples/sample_hipblaslt_ext_op_amax.rst
  docs/samples/sample_hipblaslt_ext_op_amax_with_scale.rst
  docs/samples/sample_hipblaslt_ext_op_layernorm.rst
  docs/samples/samples.rst
  docs/source-org.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-hipBLASLt.rst
Labels: documentation, ci:docs-only

#1783 update doc for swizzled fp8_in/bf16_out
  docs/reference/api-reference.rst
Labels: ci:docs-only

#1798 Added/Improved Kernels for F8NHS F8B8HS Equality Tuning
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8B8NHS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8NHS_BH_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1803 Added Equality tuning for HHS for gfx942
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bjlk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: gfx94x

#1810 Update rocisa README.md
  tensilelite/rocisa/README.md
Labels: documentation, noCI, ci:docs-only

#1811 [rocisa] doc init
  tensilelite/rocisa/docs/how-to-add-a-class.md
  tensilelite/rocisa/docs/how-to-add-a-function.md
  tensilelite/rocisa/docs/using-rocisa-in-tensilelite.md
Labels: documentation, noCI, ci:docs-only

#1813 Add copyright in rocisa CMakeLists.txt
  tensilelite/rocisa/CMakeLists.txt
Labels: documentation, noCI, ci:docs-only

#1823 dot2 kernel reject MBSK
  tensilelite/Tensile/SolutionStructs/Solution.py
  tensilelite/Tensile/Tests/common/gemm/dot2_gfx942.yaml
Labels: gfx94x

#1772 Add data type support page
  README.md
  docs/index.rst
  docs/reference/data-type-support.rst
  docs/sphinx/_toc.yml.in
  library/include/hipblaslt.h
Labels: ci:docs-only

#1847 Update README.md for new TensileLite Usage
  tensilelite/README.md
Labels: documentation, noCI, ci:docs-only

#1852 Update README.md and set Python_ROOT to /usr if not set
  tensilelite/CMakeLists.txt
  tensilelite/README.md
Labels: documentation, noCI, ci:docs-only
