Repository ROCm/hipBLASLt, pull requests merged in 2025-02, with the labels that each got.

#1540 Optimize generator
  install.sh
  tensilelite/Tensile/Source/lib/source/TensorDescriptor.cpp
  tensilelite/Tensile/Utilities/tensile_generator/README.md
  tensilelite/Tensile/Utilities/tensile_generator/tensile_config_generator.py
Labels: ci:docs-only

#1562 feature: DTVB with Swizzling (tensorB)
  tensilelite/Tensile/Components/GSU.py
  tensilelite/Tensile/KernelWriterAssembly.py
  tensilelite/Tensile/SolutionStructs.py
  tensilelite/Tensile/Source/client/source/DataInitialization.cpp
  tensilelite/Tensile/Tests/common/gemm/swizzleA.yaml
  tensilelite/Tensile/Tests/common/gemm/swizzleB.yaml
Labels: enhancement, gfx94x

#1632 Added missing swizzle argument
  clients/include/hipblaslt_common.yaml
Labels: gfx94x

#1669 Update gfx942 BBS/F8NBS TN Equality yamls for 70b prefill
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_BBS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_F8NBS_BH_BiasSB_HAS_SABV_SAV_UserArgs.yaml
Labels: gfx94x

#1693 Update TN HHS/F8NHS STA logic yamls.
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8NHS_STA_BH_BiasSH_HAS_SAB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_HHS_STA_BH_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1694 Update gfx942 HHS NN/TN Equality yamls for 0210_fp16ranking
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Ailk_Bljk_HHS_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_Bias_HAS_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/Equality/aquavanjaram_Cijk_Alik_Bljk_HHS_BH_UserArgs.yaml
Labels: gfx94x

#1698 Update TN HHS/F8NHS STA logic yamls
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8NHS_STA_BH_BiasSH_HAS_SAB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_HHS_STA_BH_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1700 Tuning: Update STA TN tuning for HHS and F8NHS
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_F8NHS_STA_BH_BiasSH_HAS_SAB_SAV_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/aquavanjaram/gfx942/GridBased/aquavanjaram_Cijk_Alik_Bljk_HHS_STA_BH_Bias_HAS_SAV_UserArgs.yaml
Labels: gfx94x

#1701 Dockerfile: build hipblaslt from latest rocm ub22.04 docker image
  docker/Dockerfile
Labels: ci:docs-only
