Repository ROCm/hipBLASLt, pull requests merged in 2025-06, with the labels that each got.

#2165 Remove F8 BC headers
  clients/benchmarks/client.cpp
  clients/benchmarks/client_sequence.cpp
  clients/common/cblas_interface.cpp
  clients/common/hipblaslt_init_device.cpp
  clients/gtest/hipblaslt_gtest_ext_op.cpp
  clients/include/allclose.hpp
  clients/include/datatype_interface.hpp
  clients/include/hipBuffer.hpp
  clients/include/hipblaslt_init.hpp
  clients/include/hipblaslt_math.hpp
  clients/include/hipblaslt_random.hpp
  clients/include/near.hpp
  clients/include/norm.hpp
  clients/include/testing_matmul.hpp
  clients/include/unit.hpp
  library/CMakeLists.txt
  library/include/hipblaslt/hipblaslt-types.h
  library/include/hipblaslt/hipblaslt_float8.h
  library/include/hipblaslt/hipblaslt_float8_bc.h
  library/src/amd_detail/hipblaslt-ext-op.cpp
  library/src/amd_detail/rocblaslt/include/rocblaslt-types.h
  library/src/amd_detail/rocblaslt/src/include/tensile_host.hpp
  library/src/amd_detail/rocblaslt/src/rocblaslt_auxiliary.cpp
  library/src/amd_detail/rocblaslt/src/tensile_host.cpp
  library/src/amd_detail/rocblaslt/src/utility.cpp
  library/src/include/auxiliary.hpp
  next-cmake/host-library/include/hipblaslt/CMakeLists.txt
  next-cmake/host-library/include/tensilelite/CMakeLists.txt
  tensilelite/Tensile/KernelWriterBetaOnly.py
  tensilelite/Tensile/KernelWriterConversion.py
  tensilelite/Tensile/Source/TensileTypes.h
  tensilelite/Tensile/Source/lib/include/Tensile/DataTypes.hpp
  tensilelite/Tensile/Source/lib/include/Tensile/DataTypes_Float8_BFloat8_bc.hpp
  tensilelite/Tensile/Source/tensile_float8_bfloat8_bc.h
  tensilelite/Tensile/TensileCreateLibrary/Run.py
Labels: gfx950

#2176 [next-cmake] Bump version
  next-cmake/CMakeLists.txt
Labels: noCI

#2171 Deprecate API hipblasltExtAMaxWithScale
  CHANGELOG.md
  CMakeLists.txt
  clients/gtest/hipblaslt_gtest_ext_op.cpp
  clients/samples/24_amax_with_scale_ext/sample_hipblaslt_ext_op_amax_with_scale.cpp
  clients/samples/24_gemm_with_TF32/sample_hipblaslt_gemm_with_TF32.cpp
  clients/samples/25_gemm_swizzle_a/sample_hipblaslt_gemm_bias_swizzle_a_ext.cpp
  clients/samples/25_gemm_swizzle_a/sample_hipblaslt_gemm_swizzle_a.cpp
  clients/samples/25_gemm_swizzle_a/sample_hipblaslt_weight_swizzle_padding.cpp
  clients/samples/26_gemm_swish_bias/sample_hipblaslt_gemm_swish_bias.cpp
  clients/samples/CMakeLists.txt
  clients/samples/common/helper.h
  docs/reference/ext-ops.rst
  docs/samples/sample_hipblaslt_ext_op_amax_with_scale.rst
  docs/samples/samples.rst
  docs/sphinx/_toc.yml.in
  library/include/hipblaslt/hipblaslt-ext-op.h
  library/src/amd_detail/hipblaslt-ext-op.cpp
  library/src/amd_detail/rocblaslt/src/extops/CMakeLists.txt
  next-cmake/CMakeLists.txt
  next-cmake/clients/samples/24_hipblaslt_ext_op_amax_with_scale/CMakeLists.txt
  next-cmake/clients/samples/24_hipblaslt_gemm_with_TF32/CMakeLists.txt
  next-cmake/clients/samples/25_hipblaslt_gemm_bias_swizzle_a_ext/CMakeLists.txt
  next-cmake/clients/samples/25_hipblaslt_gemm_swizzle_a/CMakeLists.txt
  next-cmake/clients/samples/25_hipblaslt_weight_swizzle_padding/CMakeLists.txt
  next-cmake/clients/samples/26_hipblaslt_gemm_swish_bias/CMakeLists.txt
  next-cmake/clients/samples/CMakeLists.txt
  next-cmake/device-library/extops/CMakeLists.txt
Labels: gfx950

#2188 perf. script: Avoid timeout and make this runnable on gfx950
  clients/scripts/performance/problems/matmul_probset1_bench.yaml
  clients/scripts/performance/problems/matmul_probset2_bench.yaml
  clients/scripts/performance/suites.py
Labels: runPerformance

#2197 Check if rocroller target exists before finding for super build context
  next-cmake/CMakeLists.txt
Labels: noCI

#2173 MBSK reduction uses ComputeDataType
  tensilelite/Tensile/Components/GSU.py
Labels: gfx94x, gfx950

#2205 develop branch for release after ROCm 7.0
  CMakeLists.txt
Labels: ci:docs-only

#2248 Cherry-pick to release-staging/rocm-rel-7.0: Docs/changelog: Add note about Stream-K support on MI300A (#2240)
  CHANGELOG.md
  docs/how-to/how-to-use-streamk.rst
Labels: documentation, ci:docs-only

#2238 update I8I8I liblogic to use new gfx950 mfma instructions
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx950/GridBased/gfx950_Cijk_Ailk_Bjlk_I8_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx950/GridBased/gfx950_Cijk_Ailk_Bljk_I8_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx950/GridBased/gfx950_Cijk_Alik_Bjlk_I8_BH_UserArgs.yaml
  library/src/amd_detail/rocblaslt/src/Tensile/Logic/asm_full/gfx950/GridBased/gfx950_Cijk_Alik_Bljk_I8_BH_UserArgs.yaml
Labels: gfx950

#2254 Undefine sgprGSUStartWGIdx when reduction is done
  tensilelite/Tensile/KernelWriterAssembly.py
Labels: gfx94x, gfx950
